import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Ui/Navbar";
import Footer from "./Ui/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className="bg-gray-100 overflow-x-hidden"
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
